# Generated by Django 6.0.3 on 2026-03-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_visitor_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='page',
            field=models.CharField(max_length=255),
        ),
    ]
