# Generated by Django 6.0.3 on 2026-03-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_visitor_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_github_project',
            field=models.BooleanField(default=False),
        ),
    ]
