# Generated by Django 6.0.3 on 2026-03-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_project_is_github_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_forks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='github_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='github_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='github_stars',
            field=models.IntegerField(default=0),
        ),
    ]
