# Generated by Django 6.0.3 on 2026-03-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_project_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_issues',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='github_watchers',
            field=models.IntegerField(default=0),
        ),
    ]
